#database config for ecstore database
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scnc
  host: localhost
  pool: 5
  username: root
  password: pwfcompany

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mdk2
  host: localhost
  pool: 5
  username: root
  password: pwfcompany

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scnc-sh
  pool: 5
  host: localhost
  username: root
  password: pwfcompany
